language: csharp
dotnet: 2.0.0
mono: none
services:
- docker
env:
  global:
  - secure: PBbQGZZQTKsn2lC6X3ormZEO2XEEKwyuXkQX7+6WFUAnYpSwKzfelfZkYqxuW70xfwcEab67AqLpTLvRnXsA0+elQR9n5mYpcUHY5AkrRKEGjyiRUuYlJClGD1M/T1h+rEgbZEVlXR0BM7ssyARmIbUAkcAl0KYR+ZTJ50tlcQqFmF43cGxswyWreYvXACJEqE7e8ZuRP+xKds8ECznuv7MyXKf73jQXSKEJ+rtWMP7kSiGsjEPXW6x5WnrHCY/udtNuS45zDGJ+s0KoPtyX6lGS7u+98vo35YSJgsGjpZ1qTybG7PHAo52+v9Vyi5tntOTfIcitnf19Rcw9ve3lB8h3MLdH0soPrNtJkonNxEvrNtI8YWFxrFN2L57Id6zfUmXB+/+UyW8g33KagQo95PTHFsu80vV2ZwjtT8LD29CgVHPW9g7HOlPiaQDAGOrxB1GJIXSpMj7oMZ0vOoHu7b+NQ+dAg+/73FAwUXR/my0uTsQGUFIacMuHCyNwTzZAdZgSXh45juKyN0Ntp9xzq6OyLcJaJ+dDPwn6+UVQiM9P70cJQQwGcFUtk8kl5QTqzHLGHLFFDMmNq4mRae6/ai3fkAe4yfBv0VUr/GamdHC0xEh9stNASsbg/Y94dQLhdV2aOMbLFyMI3MbPYh67wWCJ5m1clFOjk7fBIT1VY7M=
  - secure: roSiJd+eKgKD9DqNikKXx3Cz8010Wi+hsFHR84lIr4e1GLfmYLx42Vlad9LeH/uvI0QU4/f9VWXCH+Iri+g/9rrqRfHD28uJ6ARQugYt/0nt5TvlejVjvNx9KWOpYTT0/g195AbEG4qZGBYBc1Lh0LM6LtQlNCRbE3PLYnqzH/HJwdgyuMet0CdYF9D1Ko3rjVACcRCtnsOBRhNvTGgDa8pmIe9vMHuS4j82Fj49OeTXzCW3OEYOzWsRy6sTQaYJH3xrTu46XIRB81geFj7/ORHdYJQGdRg7jzqdDx4L9LYObnZj9t403QwFzvadTDawOO5o7YSRoCyQYgcrUSotY4Z+WNL7PuceoS/zh6FX7mhI/TNsRewK8R28ImgwwXc3NCxJZdWjwxAm87osYb+g/VA7SxdxfKJ3axUY8z+cGdqIAubryou1G8bk8Ti3nR551tDo76VfCd65RNP3qlw5rQbA0H3ThiS6+np4qtALDRMKE6kzdDfiteCKyYymZvOt9O7frgQAuV/cvP8yrg6HZ9AUzkS8ogmjQXFUcyl2gvJuaDzZXAmvJBnVlkAUui34QupRDS7ChD7b9tCpydpEBRuDa/8jrI8lKOOiF034hCHGo79T0ODpgAOd6o/2nPEao9tSLKH+bcGZGb4LaxXNUrPsX8nTPjEZMYGNGOukinU=
before_install:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- docker-compose build
script:
- "./test.sh"
after_success:
- eval $(aws ecr get-login --no-include-email --region ap-southeast-2)
- docker-compose build
- docker tag brycefamily:latest 896879620219.dkr.ecr.ap-southeast-2.amazonaws.com/personal.brycefamily:latest
- docker push 896879620219.dkr.ecr.ap-southeast-2.amazonaws.com/personal.brycefamily:latest
branches:
  only:
  - master
