language: csharp
dotnet: 2.0.0
mono: none
services:
- docker
env:
  global:
  secure: "I3oejzC8uve2PoPVkinnhyBdX4kmrI/+LKQEcPkeZeSsfZgUfyvWnVdKDZ2Mf4IN1XcAtK06B4+GlJuZJyHAU1U5yJxbfBLpmUneRQ94H7xUB8PYGVDCAXfupNPfpDa+EFA3d7/qLwlHCzCtvZAXD6Tw35uFQvmE6OgKmQBOgBH9ykwWayEwuKBbQbtkYrjPuGpH0EIi8l+QqHwWVQ87PjSmpdBUwmBNzNkryhUMnCUNWU6SJ+5IvHDozRPt9xwAUfAx/D2Y0r3akjio+Jk1a2gM7CxXo0HYD+mmDQNmRy9mKULeHrP6QcSXLIPXk631oOGTxfoMZof2F7kFMqp3r9X4ZzRd+uxfzn+nsrwrka2zIIuWKgRzbTV/bPTTqW41XNdqRM36zW0pDig0ceJi6W77kgVreY3TycOieR/13RG9fWahlF8NIE+3CiUXtN04xV0idVeq4HCxQ4Htrzr25B6f32z0outsSEiAkEL/Uyn9VACXqAU12Smi7MXsylwFWIZlkGeMoKcJXD0SZdyWoRe2omt7CaSokt5S/4+UYdOMKvAk4+kgnmRQXExjdAvjwFgQ5LhRCuRyfYw0R5uH41I7pkMFwMVIJFd14uC1kyyNP70m+4dNHSfrIIe0HlqICImFsq6mri4rBGfJ2AjNWK7TPCnXZdzEFPpix9F97/s="
  secure: "qIYHVXkNiL9hGbEpDPmNCk1KcHmTf0hHN/UlFuFR+RqmDkd6A1+BkcL5FVEFqAw366UlQ/YSBQmfQh2vs9hhxOSiQpRtgTHDvFNa1lmbh3agPtf/hK/q0B17r62dzXY7oylEXgdsZAZ/Z1b6GyxR9f3Zm4jkRHYujKqVjXl1xvcTtDycxbToA19V8gzLw5S1YZROZvVzZW254Ru6g7ZbTzXOx1EkjyqAm3GJiEv621Ku3NiXZ+UAVM3Og+4lAIYodb4/kiUcm7782Lm82YtSjs+u0fmERQG6QmqG95HZhF1eDWk+IqCOcAQxquZGQ3oP9E4fcAaExcDDckIjUyEJ50b0r4b7RB2BQhWZhUscAn6f9xicwuHxXVAGkE+g7wYMZeuQiMfKBRDp4s+27S5DycbpjFuWIiBBOjo8umOv86Fju5/1JaJSu++tQ28StvDNR0ApkXnkk/1iLmiGSlP7OfQwPmPCc8HG0SXwmAuMT6VWUielYmOw+x9aqKl4nQq6FPTNM41lDuIcAAtmX0V8HPA7mk/UaRBwruP1ch/OoJWymB1vwjQ3ACx7Ux0XHzgfOaUKqFD23UukzmE6HYiT1zsEWM0SEXki69Y8eYEcufP6inmDCh3nJGqyo42YScCijrZ0IMiw5pUxWS67+hzYuN8R7v97dF6jKYTRVNbZ5Do="
before_install:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- docker-compose build
script:
- "./test.sh"
after_success:
- eval $(aws ecr get-login --no-include-email --region ap-southeast-2)
- docker-compose build
- docker tag brycefamily:latest 896879620219.dkr.ecr.ap-southeast-2.amazonaws.com/personal.brycefamily:latest
- docker push 896879620219.dkr.ecr.ap-southeast-2.amazonaws.com/personal.brycefamily:latest
branches:
  only:
  - master
