language: csharp
dotnet: 2.1.0
mono: none
services:
- docker
env:
  global:
  - secure: Pg6bzbytLhhbzruebtjo+iGmf6KGtJEeyhbxuQYBkOaU8zvtJfJTz07qwcmmlycwEGcuim2VLoI/twoN4oWHw32DN1geJSJc01eDmlFZxgRIJ4MACAP7lD1oD42OmSBGxgi6ApREJp9vrew+TIyUo+JwZDiznxUGXEHLS1Nbo8QNlGLEhP5h6+l+JNWA4fbFU8TZMPt4d9ye6zP2sTTso6cSR2mkk1qL9Ta2sJl6FOnPj0OMIvzxeFiTwTy+8IVKtECo6IviM54V8FIjr+x+jKJ42aIdfUoHoLjCWLD3XhqdYfPqypv07v1A6h5w4KxUV1459XRm9tmFqFD/YCpxSqBMZywLNP9ERiCJ9WQ+mlvIz+3pJctZmGfygFJL0+JSJMbcUWGtupdQfTqw4Z+MmOxhAqasdbjo3Wl17gQa4swRJ9eHIfhW96SObNLmr8m6PghqS5DoFrvjv6kXSeVDOiGbiJ6jNFHxFItIpXDKrA206IwvSFNytFoECb1wjSNsyl+tE9S6vuPBVBVR7Iqsv5Tnztq5ESOt1c7/ZqkqNp7DtFM9n6aLDerlLCfphXe2nkE8fggQ+y/aBP+OAF9SM2NlgbYhtUn4Tk0jpPgi9J4UR4JXyweASA7FtNSEtjVF+RAjINQ0WaPvZXo4P6BKHDeu0wE0iKzVmfwJYz9F9pI=
  - secure: rPyPh4w94xJSZpC9/pms1+yGm6ZJCFDOs/lwWlXhhAqAGr9BlN9psoDeQISk/TyEslU/tj2eN8Z4phKQEJsjpOxnM1YQB7KZYwXiBAKAko6UVsK8ymphe8Y2vclNXcJ+BzU53aWnXNz4nw2x/pMgMiC756C/xBT6zaEjTnKcZwpD6KR31MEgGPohtLxqa05RUE0ofm9WqGMhhmxObvTlEFHqM+h5gzq0ACYXFSYEhkKzoirhRjy/skQBIN4zNBX+U9efv2mvii6RjVmtMc5Lve5pN/ODGVbgUI3Ds/DTFXXLAyXrATiMVNNYet9kxZViX+oMnqgHDaurH15MEM3+RB3DyngJtPZBjo2h7pN9emJ3P3Xb4hbyCnl0grb+gDE+jZA/6PsnJF232QQL99VXdgZUPUMDyPlYP2iHCUQ/n9RiB/Go11l/zjK3424cfLWolGM4usB+KI3/yJsl5Uoii4a1qE4FjI6uKGtEfbdEV+yOPRFNPiPpdGE+iyjQ5aoHnzexLtYmytNyaf7dictKQ1MOBAh4VhTL8X1LaSGFyCY9TxH4a6Je9oSLY/RjPdPnDuhXK/fFAX3mU7XKUIqamMEf9SNl8HCfXRfFGncZJ7HxEynwCGti1CPrJwt5fL6Y+VVt1tIjpTo7zm5lC7Y2jmlChx8ljtlc3IIhpaQp4e0=
before_install:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- docker-compose build
script:
- "./test.sh"
after_success:
- eval $(aws ecr get-login --no-include-email --region ap-southeast-2)
- docker-compose build
- docker tag brycefamily:latest 896879620219.dkr.ecr.ap-southeast-2.amazonaws.com/personal.brycefamily:latest
- docker push 896879620219.dkr.ecr.ap-southeast-2.amazonaws.com/personal.brycefamily:latest
branches:
  only:
  - master
